// <auto-generated />
using System;
using Glorpa.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Glorpa.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260512085137_NovaIzmjena")]
    partial class NovaIzmjena
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Glorpa.Models.Dostava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NarudzbaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VremenskiUsloviId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VrijemeDostave")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VrijemePreuzimanja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NarudzbaId")
                        .IsUnique();

                    b.HasIndex("VremenskiUsloviId");

                    b.ToTable("Dostava", (string)null);
                });

            modelBuilder.Entity("Glorpa.Models.Dug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<double>("Iznos")
                        .HasColumnType("float");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<bool>("Placeno")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId")
                        .IsUnique();

                    b.ToTable("Dug", (string)null);
                });

            modelBuilder.Entity("Glorpa.Models.Jelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RestoranId")
                        .HasColumnType("int");

                    b.Property<string>("TipJela")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RestoranId");

                    b.ToTable("Jelo", (string)null);
                });

            modelBuilder.Entity("Glorpa.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Korisnik", (string)null);
                });

            modelBuilder.Entity("Glorpa.Models.Lokacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DostavaId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("Vrijeme")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DostavaId");

                    b.ToTable("Lokacija", (string)null);
                });

            modelBuilder.Entity("Glorpa.Models.Narudzba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("NacinPlacanja")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("UkupnaCijena")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Narudzba", (string)null);
                });

            modelBuilder.Entity("Glorpa.Models.Raspored", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Sedmica")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("Raspored", (string)null);
                });

            modelBuilder.Entity("Glorpa.Models.Restoran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restoran", (string)null);
                });

            modelBuilder.Entity("Glorpa.Models.StavkaNarudzbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<int>("JeloId")
                        .HasColumnType("int");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("NarudzbaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JeloId");

                    b.HasIndex("NarudzbaId");

                    b.ToTable("StavkaNarudzbe", (string)null);
                });

            modelBuilder.Entity("Glorpa.Models.Termin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Kraj")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Pocetak")
                        .HasColumnType("datetime2");

                    b.Property<int>("RasporedId")
                        .HasColumnType("int");

                    b.Property<double>("Trajanje")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("RasporedId");

                    b.ToTable("Termin", (string)null);
                });

            modelBuilder.Entity("Glorpa.Models.VremenskiUslovi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("JeLiUslov")
                        .HasColumnType("bit");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VremenskiUslovi", (string)null);
                });

            modelBuilder.Entity("Glorpa.Models.ZahtjevPodrske", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prioritet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipZahtjeva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.ToTable("ZahtjevPodrske", (string)null);
                });

            modelBuilder.Entity("Glorpa.Models.Zarada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("DostavaId")
                        .HasColumnType("int");

                    b.Property<double>("Iznos")
                        .HasColumnType("float");

                    b.Property<double>("Sat")
                        .HasColumnType("float");

                    b.Property<int>("TipZarade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DostavaId")
                        .IsUnique();

                    b.ToTable("Zarada", (string)null);
                });

            modelBuilder.Entity("Glorpa.Models.Dostava", b =>
                {
                    b.HasOne("Glorpa.Models.Narudzba", "Narudzba")
                        .WithOne("Dostava")
                        .HasForeignKey("Glorpa.Models.Dostava", "NarudzbaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Glorpa.Models.VremenskiUslovi", "VremenskiUslovi")
                        .WithMany("Dostave")
                        .HasForeignKey("VremenskiUsloviId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Narudzba");

                    b.Navigation("VremenskiUslovi");
                });

            modelBuilder.Entity("Glorpa.Models.Dug", b =>
                {
                    b.HasOne("Glorpa.Models.Korisnik", "Korisnik")
                        .WithOne("Dug")
                        .HasForeignKey("Glorpa.Models.Dug", "KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("Glorpa.Models.Jelo", b =>
                {
                    b.HasOne("Glorpa.Models.Restoran", "Restoran")
                        .WithMany("Jela")
                        .HasForeignKey("RestoranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restoran");
                });

            modelBuilder.Entity("Glorpa.Models.Lokacija", b =>
                {
                    b.HasOne("Glorpa.Models.Dostava", "Dostava")
                        .WithMany("Lokacije")
                        .HasForeignKey("DostavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dostava");
                });

            modelBuilder.Entity("Glorpa.Models.Narudzba", b =>
                {
                    b.HasOne("Glorpa.Models.Korisnik", "Korisnik")
                        .WithMany("Narudzbe")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("Glorpa.Models.Raspored", b =>
                {
                    b.HasOne("Glorpa.Models.Korisnik", "Korisnik")
                        .WithMany("Rasporedi")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("Glorpa.Models.StavkaNarudzbe", b =>
                {
                    b.HasOne("Glorpa.Models.Jelo", "Jelo")
                        .WithMany("StavkeNarudzbe")
                        .HasForeignKey("JeloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Glorpa.Models.Narudzba", "Narudzba")
                        .WithMany("StavkeNarudzbe")
                        .HasForeignKey("NarudzbaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jelo");

                    b.Navigation("Narudzba");
                });

            modelBuilder.Entity("Glorpa.Models.Termin", b =>
                {
                    b.HasOne("Glorpa.Models.Raspored", "Raspored")
                        .WithMany("Termini")
                        .HasForeignKey("RasporedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raspored");
                });

            modelBuilder.Entity("Glorpa.Models.ZahtjevPodrske", b =>
                {
                    b.HasOne("Glorpa.Models.Korisnik", "Korisnik")
                        .WithMany("ZahtjeviPodrske")
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");
                });

            modelBuilder.Entity("Glorpa.Models.Zarada", b =>
                {
                    b.HasOne("Glorpa.Models.Dostava", "Dostava")
                        .WithOne("Zarada")
                        .HasForeignKey("Glorpa.Models.Zarada", "DostavaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dostava");
                });

            modelBuilder.Entity("Glorpa.Models.Dostava", b =>
                {
                    b.Navigation("Lokacije");

                    b.Navigation("Zarada")
                        .IsRequired();
                });

            modelBuilder.Entity("Glorpa.Models.Jelo", b =>
                {
                    b.Navigation("StavkeNarudzbe");
                });

            modelBuilder.Entity("Glorpa.Models.Korisnik", b =>
                {
                    b.Navigation("Dug")
                        .IsRequired();

                    b.Navigation("Narudzbe");

                    b.Navigation("Rasporedi");

                    b.Navigation("ZahtjeviPodrske");
                });

            modelBuilder.Entity("Glorpa.Models.Narudzba", b =>
                {
                    b.Navigation("Dostava")
                        .IsRequired();

                    b.Navigation("StavkeNarudzbe");
                });

            modelBuilder.Entity("Glorpa.Models.Raspored", b =>
                {
                    b.Navigation("Termini");
                });

            modelBuilder.Entity("Glorpa.Models.Restoran", b =>
                {
                    b.Navigation("Jela");
                });

            modelBuilder.Entity("Glorpa.Models.VremenskiUslovi", b =>
                {
                    b.Navigation("Dostave");
                });
#pragma warning restore 612, 618
        }
    }
}
